maven_build:
    image:  maven:3-jdk-8
    script: mvn -B clean install deploy site-deploy -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts
    only:
        - main

maven_release:
    image: maven:3-jdk-8
    script:
        - git config user.email "${GITLAB_USER_EMAIL}"
        - git config user.name "${GITLAB_USER_NAME}"
        - git checkout -B "${CI_BUILD_REF_NAME}"
        - mvn -B clean release:prepare release:perform site-deploy -DfullBuild -s ci_settings.xml -P clean-dependencies,!sign-artifacts -DreleaseProfiles=clean-dependencies,!sign-artifacts -Dusername=${ci_git_user} -Dpassword=${ci_git_token}
    only:
        - release

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
sast:
    stage: test
    variables:
        SAST_JAVA_VERSION: 8

include:
    - template: Security/SAST.gitlab-ci.yml
