# This is a basic workflow to help you get started with Actions

name: Maven - Release Build

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for version branches
    push:
        branches: ["version/release/*"]
    pull_request:
        branches: ["version/release/*"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    release:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -
                name: Git Checkout
                uses: actions/checkout@v4
            -
                name: Setup git user
                run:  |
                      git config --global user.name "ChrissW-R1"
                      git config --global user.email "contact@ChrissW-R1.me"
            -
                name: Setup JDK 21
                uses: actions/setup-java@v4
                with:
                    distribution:    'temurin'
                    java-version:    '21'
                    cache:           maven
                    server-id:       project-repo # Value of the distributionManagement/repository/id field of the pom.xml
                    settings-path:   ${{ github.workspace }} # location for the settings.xml file
                    gpg-passphrase:  'gpg_passphrase'
                    gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
            -
                name: Build with Maven
                run:  mvn -B clean release:prepare release:perform -DfullBuild -s ci_settings.xml --file pom.xml -Dusername=${ci_git_user} -Dpassword=${GITHUB_TOKEN} -DignoreSnapshots=true
                env:
                    GITHUB_TOKEN:             ${{ secrets.GITHUB_TOKEN }}
                    ci_git_user:              ${{ env.CI_GIT_USER }}
                    nvd_api_key:              ${{ secrets.NVD_API_KEY }}
                    gpg_key:                  ${{ secrets.GPG_PRIVATE_KEY }}
                    gpg_keyid:                ${{ secrets.GPG_KEYID }}
                    gpg_passphrase:           ${{ secrets.GPG_PASSPHRASE }}
                    mvnsiteuploader_password: ${{ secrets.MVNSITEUPLOADER_PASSWORD }}
